### ISSUE TITLE
emapplot gives error in version 3.18.1 and not in 3.14.0

### ISSUE THREAD

**Issue by flomehl** [YuLab-SMU/enrichplot#112]
Hello,
I was using emapplot and it worked nicely but it seems that a problem is occuring with the version I use now (clusterProfiler v3.18.1, R version 4.0.3). I tried the same input file in R version 3.6.1 with clusterProfiler v3.14.0 and it worked.
here is the error:
Error in has_pairsim(x) : 
  Term similarity matrix not available. Please use pairwise_termsim function to deal with the results of enrichment analysis.
Do you know if something has changed?
thanks a lot,
cheers
Florence

**Comment by aoumess** [comment]
Hi !
I have the same error for enrichplot v1.10.2 in R.4.0.4 (installed yesterday)

**Comment by huerqiang** [comment]
It will help: https://github.com/YuLab-SMU/enrichplot/issues/79

**Comment by aoumess** [comment]
> It will help: #79

Thanks for the tip !
It probably would help if it was written in the function help page :)
