### ISSUE TITLE
Why I can't find the gsinfo function in enrichplot

### ISSUE THREAD

**Issue by chaozhengzhou** [YuLab-SMU/enrichplot#116]
Why I can't find the gsinfo function in enrichplot. I want to extract GSEA results using gsinfo() to costomize my gsea plot.

**Comment by huerqiang** [comment]
We don't have a `gsinfo` function in `enrichplot`, maybe you want to use `gsInfo` : 
```r
enrichplot:::gsInfo
```

**Comment by GuangchuangYu** [comment]
this function is only for internal use.
