### ISSUE TITLE
'showCategory=description_of_interest' for compareCluster results?

### ISSUE THREAD

**Issue by ellchua** [YuLab-SMU/enrichplot#123]
Hi, 

How can I show the descriptions of interest in the dotplot of my compareCluster object? I tried the suggestion mentioned [here](https://www.biostars.org/p/360453/) but it doesn't seem to work.

**Comment by GuangchuangYu** [comment]
should be fixed by <https://github.com/YuLab-SMU/enrichplot/pull/125>.

Another solution is to use `filter` method to screen out the result before using `dotplot`, see also <https://yulab-smu.top/biomedical-knowledge-mining-book/clusterProfiler-dplyr.html>.
