### ISSUE TITLE
What units is the x-axis in ridgeplot in?

### ISSUE THREAD

**Issue by msteph11** [YuLab-SMU/enrichplot#124]
Hi,

I used clusterProfiler to perform GSEA, using log2 fold changes for my genesList. I then visualized the GSEA result, using the ridgeplot function from enrichplot, but am not sure what units the x-axis is in. Is the x-axis log2 fold change? I tried looking at the documentation, but couldn't find a clear answer, so I thought I'd ask.

Thanks,
Maria

**Comment by huerqiang** [comment]
If your input is log2FC, then the x-axis represents the log2FC of the genes.

**Comment by msteph11** [comment]
Thanks!!

**Comment by msteph11** [comment]
So just to confirm, the x-axis is whatever was used as input, correct?

**Comment by huerqiang** [comment]
Yes.
