### ISSUE TITLE
cnetplot for list object

### ISSUE THREAD

**Issue by itsvenu** [YuLab-SMU/enrichplot#147]
Hi,

Thanks for the very nice package. I am trying to use `cnetplot` function with a list object. However, I get the following error. In the manual, it is written that the function can be used for a named list object, [here](https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#fig:cnetplotgeneral).

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘cnetplot’ for signature ‘"list"’
```

Any help is greatly appreciated in solving this issue. Thank you!

**Comment by itsvenu** [comment]
@huerqiang Thanks for the quick reply. Seems to be working.

**Comment by abiodunodufuwa** [comment]
@huerqiang please i am having same problem. The version of enrichplot i am using is 1.10.2
in my first attempt, I used this command 
x <- list(A = Enrich2_RNAseq_sig_BP[134,9], B= DMR_BP_rich[8,8])
p <- cnetplot(x)

in the second attempt i created the two list first as follows
Axonogenese_rnaseq_enrich_gene <- as.list(Enrich2_RNAseq_sig_BP[134,9])
Axonogenese_DMR_enrich_gene <- as.list(DMR_BP_rich[8,8])
x1 <- list(A = Axonogenese_DMR_enrich_gene, B = Axonogenese_rnaseq_enrich_gene)
p1 <- cnetplot(x1)

For the two approaches, i am getting the error message " Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘cnetplot’ for signature ‘"list"’"
Please, what am I doing wrong? kindly help me.

Thank you

**Comment by huerqiang** [comment]
@abiodunodufuwa 
Your enrichplot package is out of date. Please update it. And your input seems inappropriate. Please see: https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#fig:cnetplotgeneral
