### ISSUE TITLE
label interested genes on cnetplot

### ISSUE THREAD

**Issue by HTL2010** [YuLab-SMU/enrichplot#152]
Hi,

I am making plot using cnetplot. The problem is there is too many labels (genes). Is it possible to only label the gene nodes with top 20 fold change? 

Any advice is greatly appreciated! Thanks!

**Comment by KR-15** [comment]
Hi, 

I have exactly the same kind of request. I would like to label specific node (gene) of interest without labelling everything.

Did you find any solution since then ?

Best,

KR

**Comment by HTL2010** [comment]
Hi,

I don't have solution for this question.

HL

**Comment by huerqiang** [comment]
At present,  adding labels to part of  genes is not supported. We may support it in a later version.

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/enrichplot/issues/253>.
