### ISSUE TITLE
关于gseaplot2()添加ggplot2图层的问题

### ISSUE THREAD

**Issue by HengqiLiu** [YuLab-SMU/enrichplot#154]
想基于gseaplot2()做出的图做一些个性化的添加，但是按照ggplot2的方法，一层一层的添加图层好像不可以
例如
`p= gseaplot2(gsea_NT5E,
                                   geneSetID = ID_NT5E,
                                   # pvalue_table = T,
                                   base_size =9,
                                   color = "#63be48",
                                   subplots = 1:2,
                                   title = ID_NT5E) + 
    annotate("text", x = 4, y = 25, label = "add text",color="orange",size = 5, angle=45, fontface="bold" ) `

想问一下是我写的作图代码有问题嘛，万分感谢🙏🙏🙏

**Comment by huerqiang** [comment]
`gseaplot2`支持使用ggplot2添加图层，但`gseaplot2`是三个图合并到一起的，你直接添加会加到最后一个图上。你如果想添加到第一个图（最上面的图），可以用：
```r
p <- gseplot2(...)
p[[1]] <- p[[1]] + annotate(...)
p
```
你说的“好像不可以”，不知道你有没有试着改变annotate的位置，，，，，

**Comment by HengqiLiu** [comment]
我明白了老师，谢谢您！！！

**Comment by jijitoutou** [comment]
> `gseaplot2`支持使用ggplot2添加图层，但`gseaplot2`是三个图合并到一起的，你直接添加会加到最后一个图上。你如果想添加到第一个图（最上面的图），可以用：
> 
> ```r
> p <- gseplot2(...)
> p[[1]] <- p[[1]] + annotate(...)
> p
> ```
> 
> 你说的“好像不可以”，不知道你有没有试着改变annotate的位置，，，，，
请问博主，cnetplot()函数可以基于pvalue输出富集分析的结果吗？谢谢！

**Comment by huerqiang** [comment]
你说的“基于pvalue输出富集分析的结果”具体指的是什么，是根据pvalua筛选富集结果，还是用pvalue给cnetplot的基因节点着色？

**Comment by jijitoutou** [comment]
> 你说的“基于pvalue输出富集分析的结果”具体指的是什么，是根据pvalua筛选富集结果，还是用pvalue给cnetplot的基因节点着色？

想实现根据pvalua筛选富集结果，默认是根据p.adjust输出的。请博主提供下参数设置的代码，谢谢。

**Comment by huerqiang** [comment]
@jijitoutou 可以用[filter](https://yulab-smu.top/biomedical-knowledge-mining-book/clusterProfiler-dplyr.html)来筛选。

**Comment by jijitoutou** [comment]
> @jijitoutou 可以用[filter](https://yulab-smu.top/biomedical-knowledge-mining-book/clusterProfiler-dplyr.html)来筛选。

即便筛选保留了p value小于0.05的结果，出图的时候还是会默认依据p.adj这一列结果输出

**Comment by huerqiang** [comment]
@jijitoutou 你应该首先确保你的富集结果保留了pvalue < 0.05的，而不是p.adj < 0.05。出图并不会筛选你的p.adj。

**Comment by jijitoutou** [comment]
> @jijitoutou 你应该首先确保你的富集结果保留了pvalue < 0.05的，而不是p.adj < 0.05。出图并不会筛选你的p.adj。

是的 我查看了表 就是这样的情况。但是出不来图。
之前有一次出图，我想按照qvalue出图，qvalue有10个结果，p.adj有9个结果，最后我数了，通路只有9个

**Comment by huerqiang** [comment]
@jijitoutou 你这个非常好解决，只要看一下自己的参数有没有使用p.adj进行筛选就可以了。你如果想完全按照pvalue进行筛选，在富集分析是就不要使用参数对pvalue和qvalue进行筛选（即阈值改为1），然后用filter筛选。
