### ISSUE TITLE
No dotplot signature found for compareClusterResult class

### ISSUE THREAD

**Issue by ShixiangWang** [YuLab-SMU/enrichplot#155]
Hi guys,

I am trying to split long labels across multiple lines using approach described at https://yulab-smu.top/biomedical-knowledge-mining-book/faq.html?q=wrap#label-format but not work.

```r
> library(enrichplot)
> p3 = dotplot(ck_go_cc_sp, showCategory = 20, label_format = function(x) stringr::str_wrap(x, width=20))
Error in .local(object, ...) : 
  unused argument (label_format = function (x) 
stringr::str_wrap(x, width = 20))
> ?dotplot
> class(ck_go_cc_sp)
[1] "compareClusterResult"
attr(,"package")
[1] "DOSE"
```

I checked the function documentation and found no related signature for the `compareClusterResult` object. So `label_format` is not supported.

![image](https://user-images.githubusercontent.com/25057508/144371982-75e8de6e-b6c6-4145-9ccf-3cf5e1b690ba.png)

Best,

Shixiang

**Comment by GuangchuangYu** [comment]
you may use an outdated version.

**Comment by ShixiangWang** [comment]
@GuangchuangYu Thanks for pointing out.
