### ISSUE TITLE
list2graph function not find

### ISSUE THREAD

**Issue by jupollet** [YuLab-SMU/enrichplot#18]
Hi, 

I would like to have an igraph object from the graph produced by cnetplot function.
I'm not sure but I think it's possible with the **list2graph** function.
So, I installed 1.3.2 version of enrichplot packages : 
```
install.packages("devtools")
library(devtools)
install_github("GuangchuangYu/enrichplot")
```
All function of enrichlot is find by R but not **list2graph**.

Thank you in advance.

**Comment by GuangchuangYu** [comment]
not an exported function
