### ISSUE TITLE
Add dotplot color options to plot top categories by NES: absNES, posNES, negNES

### ISSUE THREAD

**Issue by hermidalc** [YuLab-SMU/enrichplot#186]
It's more appropriate for GSEA enrichment results to look at the top categories by `NES` not `pvalue` or `p.adjust`. Would be able to add three `color` options, `absNES` for `abs(NES)`, `negNES` for sorted ascending, and `posNES` for sorted descending, so that ppl can choose to plot top categories or these?

**Comment by hermidalc** [comment]
Similar to #14, but feature request here is hopefully more because you don't always want to plot only top posNES, you want to show enrichment on both sides of ranked list or one negNES side.

**Comment by GuangchuangYu** [comment]
already supported in github version to color by 'NES'. 

For absNES, posNES, negNES, you should refer to the dplyr verb provided in `clusterProfiler` for processing enrichment result, see <https://pubmed.ncbi.nlm.nih.gov/34557778/>.
