### ISSUE TITLE
Make pathwyas names bold in cnetplot

### ISSUE THREAD

**Issue by eleonore-schneeg** [YuLab-SMU/enrichplot#194]
Hi,

I'm trying to bold the pathwyas names in this cnetplot

 cnetplot(list_data, foldChange=d,
               categorySize=1,
               colorEdge=F,
               cex_label_category = 0.3,
               vertex_size=0.1,
               cex_label_gene = 0.3,
               color_category=list_color, 
               layout='kk',
               font=2,
               color_gene='steelblue',showCategory = 150) 

Any idea on how to proceed?

Thanks

**Comment by huerqiang** [comment]
@eleonore-schneeg We currently do not provide a parameter to bold the pathway name, but we can modify its size useing `cex_label_category`.

**Comment by GuangchuangYu** [comment]
supported, with github version of [ggtangle](https://github.com/YuLab-SMU/ggtangle) or v >= 0.0.4.002


```
library(ggtangle)
library(ggplot2)

set.seed(123)
x <- list(A = letters[1:10], B=letters[5:12], C=letters[sample(1:26, 15)])

p1 <- cnetplot(x, node_label="none")
p1 + geom_cnet_label(node_label = 'all', fontface='bold', bg.r=.2)

```

![image](https://github.com/user-attachments/assets/27a7c6fc-4bfd-4f19-aec9-a29f35ca8b0e)
