### ISSUE TITLE
Missing categorySize argument in cnetplot

### ISSUE THREAD

**Issue by Feat-FeAR** [YuLab-SMU/enrichplot#196]
Thank you for your effort in developing and maintaining this software.
Now I'm trying using `enrichplot::cnetplot` function following your tutorial at
https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html
but it seems that the `categorySize` argument is no more implemented in it... am I right?
Is there maybe a new way to control this feature? Or, as an alternative, can I get rid of the circle-size legend on the right side of the plot since it is drawn by default but has currently no meaning?
Thanks

**Comment by huerqiang** [comment]
<html>
<body>


cex_category | Number indicating the amount by which plotting category nodes should be scaled relative to the default, the default value is 1. Will be removed in the next version.
-- | --
cex_gene | Number indicating the amount by which plotting gene nodes should be scaled relative to the default, the default value is 1. Will be removed in the next version.
cex_label_category | Scale of category node label size, the default value is 1. Will be removed in the next version.
cex_label_gene | Scale of gene node label size, the default value is 1. Will be removed in the next version.


</body>
</html>

**Comment by huerqiang** [comment]
cnetplot(x2) + theme(legend.position = 'none')

**Comment by Feat-FeAR** [comment]
> cex_category	Number indicating the amount by which plotting category nodes should be scaled relative to the default, the default value is 1. Will be removed in the next version.
> cex_gene	Number indicating the amount by which plotting gene nodes should be scaled relative to the default, the default value is 1. Will be removed in the next version.
> cex_label_category	Scale of category node label size, the default value is 1. Will be removed in the next version.
> cex_label_gene	Scale of gene node label size, the default value is 1. Will be removed in the next version.

Thank you @huerqiang for your super fast reply! I noticed those options, but they are _global_ settings. The old `categorySize` argument allowed instead for gene-specific size adjustment. I guess this is no more possible, right?

**Comment by khsara** [comment]
I would have the same issue, I am trying to get the `categorySize` argument to be based on `categorySize="p.adjust"` or `categorySize="pvalue"` but seems like it keeps returning the default which is sizing based on the `categorySize="geneNum"`. would it be possible to adjust the categorySize based on p value? and if not would it then be possible to not  have the sizing based anything?

**Comment by hwick** [comment]
I am also having this issue. I set categorySize to pvalue, but the legend shows "size" instead of p value and there is no difference to graphs where I do not specify categorySize. Oddly, I get a warning message that size has already been set, no matter whether I include that argument or not. CategorySize is not mentioned in the help documentation. Additionally, in [this chapter](https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html) it shows with and without setting categorySize to pvalue, and even their own plots don't show the legend reflecting that, and there is no discernible difference between the two plots, at least to my eyes. Did this argument ever do anything? **What exactly are the gene set node sizes being scaled to?**

```
> cnetplot(ego, 
Warning messages:
+          categorySize="pvalue", 
+          showCategory = 5, 
+          foldChange=OE_foldchanges, 
+          vertex.label.font=6)
Scale for size is already present.
Adding another scale for size, which will replace the existing scale.
Warning messages:
1: In cnetplot.enrichResult(x, ...) :
  Use 'color.params = list(foldChange = your_value)' instead of 'foldChange'.
 The foldChange parameter will be removed in the next version.
2: ggrepel: 500 unlabeled data points (too many overlaps). Consider increasing max.overlaps

> cnetplot(ego, 
+          showCategory = 5, 
+          foldChange=OE_foldchanges, 
+          vertex.label.font=6)
Scale for size is already present.
Adding another scale for size, which will replace the existing scale.
Warning messages:
1: In cnetplot.enrichResult(x, ...) :
  Use 'color.params = list(foldChange = your_value)' instead of 'foldChange'.
 The foldChange parameter will be removed in the next version.
2: ggrepel: 500 unlabeled data points (too many overlaps). Consider increasing max.overlaps
```

**Comment by GuangchuangYu** [comment]
in new version, pls use `size_category` parameter.
