### ISSUE TITLE
`goplot` fails with `gseGO` result: Error in getAncestors(x@ontology): no slot of name "ontology" for this object of class "gseaResult"

### ISSUE THREAD

**Issue by hermidalc** [YuLab-SMU/enrichplot#204]
When I run `gseGO` if I then use the result in a `goplot` I get the error:
```R
goplot(y)

y <- gseGO(
    ranks,
    ont = "BP",
    org.Mm.eg.db,
    keyType = "SYMBOL",
    minGSSize = 15,
    maxGSSize = 500,
    eps = 0.0,
    pvalueCutoff = 0.1,
    pAdjustMethod = "BH",
    seed = 777,
    nPermSimple = 10000,
    by = "fgsea"
)

goplot(y)
```
```R
Error in getAncestors(x@ontology) : 
  no slot of name "ontology" for this object of class "gseaResult"
```

**Comment by hermidalc** [comment]
When I try manually setting:
```R
y@ontology <- "BP"
Error in (function (cl, name, valueClass)  : 
  ‘ontology’ is not a slot in class “gseaResult”
```

I'm really confused because `goplot` is supposed to support `gseaResult`

**Comment by hermidalc** [comment]
Looking at the source code I don't understand why this is failing, it should look at `y@setType` not `y@ontology` for a `gseaResult`. And I double checked my `class(y)` is a `gseaResult` and `inherits(y, "gseaResult")` is `TRUE`

https://github.com/YuLab-SMU/enrichplot/blob/master/R/goplot.R#L44-48

**Comment by hermidalc** [comment]
Here's a reprex:
```R
library(clusterProfiler)
library(enrichplot)
library(org.Hs.eg.db)

data(geneList, package="DOSE")

ego <- gseGO(
    geneList     = geneList,
    OrgDb        = org.Hs.eg.db,
    ont          = "CC",
    minGSSize    = 100,
    maxGSSize    = 500,
    pvalueCutoff = 0.05,
    verbose      = FALSE
)
goplot(ego)
```
```R
Error in getAncestors(x@ontology) : 
  no slot of name "ontology" for this object of class "gseaResult"
```

**Comment by huerqiang** [comment]
Please use the latest version of `DOSE` and `enrichplot`
![image](https://user-images.githubusercontent.com/48857018/198856965-b3e70b79-ebd8-494d-98e3-294175f4c653.png)

**Comment by hermidalc** [comment]
Please if you can update the latest available on bioconda, many people use conda for their package management and latest avail on bioconda is `4.2.0`
