### ISSUE TITLE
Treeplot in the latest enrichplot package still have problem

### ISSUE THREAD

**Issue by YanCC506** [YuLab-SMU/enrichplot#209]
In command "treeplot" from the latest enrichplot package, the parametre "showCategory" doesn't work, no matter it was setted as a number or vector, the plot always display 30 terms...

**Comment by huerqiang** [comment]
Please make sure that you are using the latest version of `enrichplot` and have read the documentation.

**Comment by YanCC506** [comment]
My R version is the latest 4.22, I have tried the code "treeplot" from the
1.18.0 version of enrichplot package from Bioconductor and the 1.19.0
version from github, even i run the example code in the R Documentation and
set the showCategory as any other number except 30, the result always show
30 terms. The only way is to modify the parametre of showCategory in the
souce code fie "treeplot.R" and reload the package. And I have to say that
this method is a bit complicated...

Erqiang Hu ***@***.***> 于2022年11月14日周一 09:23写道：

**Comment by YanCC506** [comment]
I have fixed the problem by myself. The cause of this problem is in the source code "treplot.R". Code that deifnes showCategory in "setMethod-function" part was removed in the latest version of enrichplot packages, causing all subsequent algorithms to run at showCategory=30.

**Comment by huerqiang** [comment]
Thanks, we will fix it in the next version.

**Comment by GuangchuangYu** [comment]
fixed in v >= 1.8.1
