### ISSUE TITLE
Cnet Plot Color Scale

### ISSUE THREAD

**Issue by XuTianhao** [YuLab-SMU/enrichplot#21]
Dear Dr. Yu,

I'm using your Cnetplot in your Cluster Profiler package, one of the enrichGO output I ran on the Cnetplot I found that the color scale skewed towards FC>0. Could you let me know what might be the problem and how to fix it? Thank you in advance.
<img width="652" alt="Screen Shot 2019-04-09 at 6 13 30 PM" src="https://user-images.githubusercontent.com/17917370/55841110-8cf61100-5af3-11e9-95d4-08c315d545db.png">

**Comment by GuangchuangYu** [comment]
fixed, see also <https://github.com/YuLab-SMU/enrichplot/issues/39>.
