### ISSUE TITLE
Where to find geneSetID

### ISSUE THREAD

**Issue by Lesdormis** [YuLab-SMU/enrichplot#23]
Dear Dr. Yu

Hi, I am very interested to use entichplot to generate the GSEA plot which would save a lot of work for me. But I am very confusing about the geneSetID argument in the gseaplot function. 
I noticed you used 1 or 1:3 for that, but what if I want to use my interested gene set where can I find my gene set ID. And whenever I didn't put 1 in that argument I get an error said 
Error in if (abs(max.ES) > abs(min.ES)) { : missing value where TRUE/FALSE needed

Many thanks,
Shaowen

**Comment by BrianLohman** [comment]
Hello,

I'd like an answer to this as well. The reference documentation is missing a description for the geneSetID parameter. 

Is there a place where we can find full description of the arguments, the structure of the input data, and an working example?

Cheers,

Brian

**Comment by RichardJActon** [comment]
From experimenting I have inferred that the geneSetID parameter controls which of the gene sets to highlight in the plot
by default it the the first 3, but can be a numeric vector indicating the index of the row of the set you want highlighted on the plot.
The error `Error in if (abs(max.ES) > abs(min.ES)) { : missing value where TRUE/FALSE needed` appears to occur when you specify an index that is greater than the number of rows. 

This would indeed benefit from documenting and improved error handling when and out of range value is supplied - I may open a PR when I get the time

**Comment by TiongSun** [comment]
The geneSetID is the index in the @result dataframe within your gseaResults object. You can access using the code :

df <- Your_gseaResults@result

Hope that helps. Thanks!

**Comment by Jeff-Gui** [comment]
Hi, I am using clusterProfiler 3.18.1 and enrichplot 1.10.2. I cannot find geneSetID column in the gsearResult object. The columns are  "ID"   "Description"     "setSize"         "enrichmentScore" "NES"             "pvalue"          "p.adjust"        "qvalues"   "rank"   "leading_edge"    "core_enrichment"

**Comment by huerqiang** [comment]
@Jeff-Gui  TiongSun  has described it very clearly. For details, please visit :
https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#running-score-and-preranked-list-of-gsea-result

**Comment by kelly-sovacool** [comment]
> @Jeff-Gui TiongSun has described it very clearly. For details, please visit : https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#running-score-and-preranked-list-of-gsea-result

There is not an explanation of geneSetID in the docs you linked. I could only figure it out by finding this issue. If the description in [TiongSun's comment](https://github.com/YuLab-SMU/enrichplot/issues/23#issuecomment-884640091) were added to the docs, that would help immensely.

@GuangchuangYu can you reopen this issue?

**Comment by FilipeFerreiraMOCHSL** [comment]
Hi, thanks for this awesome R package!

Indeed, the documentation is not super clear about this, although we can infer that.

For those like me who were confused: the "geneSetID" parameter is simply the enriched terms in your analysis! So, you can find them exactly by running any of the following command = your_gse_object$Description OR your_gse_object@result (ID or Description columns)

The number you pass for this parameter matches the list / row table order from the above mentioned commands!

I hope this helps!

Best
