### ISSUE TITLE
Use enrichment result dataframe from WebGestaltR

### ISSUE THREAD

**Issue by Pweidemueller** [YuLab-SMU/enrichplot#24]
Hey YuLab,

I was used to do my Over Representation Analysis with the WebGestaltR package and only now discovered your clusterProfiler package. For my next analysis I think I will switch, but for now I need to stick with the results obtained by WebGestalt since I already started downstream analysis with that output. Your enrichplot package has all the plots I would also like to generate. Is there a way to convert the WebGestalt enrichment result (dataframe) into the required object as input for e.g. cnetplot. 
Attached find an example dataframe that results from a WebGestalt over representation analysis.
[WebGestaltORA_output_example.txt](https://github.com/YuLab-SMU/enrichplot/files/3546511/WebGestaltORA_output_example.txt)

**Comment by GuangchuangYu** [comment]
`enrichplot` only works with `clusterProfiler`, `DOSE`, `meshes` and `ReactomePA` outputs.
