### ISSUE TITLE
dotplot warning

### ISSUE THREAD

**Issue by bounlu** [YuLab-SMU/enrichplot#28]
When `orderBy` parameter  is not explicitly set, it gives unnecessary warning as below:

`wrong orderBy parameter; set to default orderBy = "x"`

I digged into the code in dotplot.R and it must be coming from these lines:

>     if (orderBy !=  'x' && !orderBy %in% colnames(df)) {
>         message('wrong orderBy parameter; set to default `orderBy = "x"`')
>         orderBy <- "x"
>     }

It seems somehow the default value `orderBy="x"` is not read.

**Comment by GuangchuangYu** [comment]
no. that's because you are using an out-dated version.

**Comment by bounlu** [comment]
I'm using v1.4.0 which is the latest version installed by default with `BiocManager::install("enrichplot")` and have this problem.

**Comment by GuangchuangYu** [comment]
currently v1.6.0.

```
> rvcheck::check_bioc("enrichplot")
devel branch is used, this function only works for release version...
$package
[1] "enrichplot"

$installed_version
[1] "1.7.1"

$latest_version
[1] "1.6.0"

$up_to_date
[1] NA

> date()
[1] "Thu Nov 14 11:21:25 2019"
```

**Comment by bounlu** [comment]
somehow I don't get v1.6.0 through the BiocManager, is it because you installed the devel version? can you push v1.6.0 to the Bioconductor?

**Comment by GuangchuangYu** [comment]
can you check the webpage in Bioconductor? I can't do that for you.

**Comment by kirushka** [comment]
I have this warning with v1.6.0

**Comment by GuangchuangYu** [comment]
should be removed with v>= 1.6.1

**Comment by rrydbirk** [comment]
Still persisting in v. 1.11.1
