### ISSUE TITLE
Apparent small issue with latest version installation from github?!

### ISSUE THREAD

**Issue by mihaelaolaRCSI** [YuLab-SMU/enrichplot#30]
There seems to be a small issue with installation of latest version of enrichplot from github:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'DOSE' 3.13.0 is being loaded, but >= 3.13.1 is required

The latest version of DOSE available is 3.13.0 though (13 Nov 2019)?! Thank you so much for all the tools and the hard work put into it!

**Comment by huerqiang** [comment]
The latest version of DOSE available is 3.13.1 in the github: https://github.com/YuLab-SMU/DOSE.
You can install it by using: `devtools::install_github("YuLab-SMU/DOSE")`.

**Comment by mihaelaolaRCSI** [comment]
Thank you so so much for the prompt response! I don't know how I missed that.. Saw 13 Nov in the manual and assumed that was no way there's a newer version... Thank you so much, again!
