### ISSUE TITLE
error with barplot/dotplot: 'decode_colour' is not an exported object from 'namespace:farver'

### ISSUE THREAD

**Issue by giggu98** [YuLab-SMU/enrichplot#33]
Hello,

I've tried generating a GO enrichment plot using enrichplot but such error occurred. I guess it is the issue about the lack of package/ outdated version of the package I have but cannot figure out what I missed or has to update.

The full error text is as followings: 

`Error: 'decode_colour' is not an exported object from 'namespace:farver'`

Thank you in advance for your help
Best Regards,

**Comment by huerqiang** [comment]
> Hello,
> 
> I've tried generating a GO enrichment plot using enrichplot but such error occurred. I guess it is the issue about the lack of package/ outdated version of the package I have but cannot figure out what I missed or has to update.
> 
> The full error text is as followings:
> 
> `Error: 'decode_colour' is not an exported object from 'namespace:farver'`
> 
> Thank you in advance for your help
> Best Regards,
Dear giggu98,
Please provide your data and codes. I can't give you a solution without knowing your code.

**Comment by GuangchuangYu** [comment]
we didn't import `decode_colour` from `farver`, see <https://github.com/YuLab-SMU/enrichplot/blob/master/NAMESPACE>.

This may caused by an error of a dependent package. A reproducible example with session info would be helpful.
