### ISSUE TITLE
The install problem

### ISSUE THREAD

**Issue by rusher321** [YuLab-SMU/enrichplot#37]
Hi, Guang chuang:
When I installed your package **enrichplot** in the R 3.61,  I got the error:
namespace 'DOSE' 3.12.0 is being loaded, but >= 3.13.1 is required

But, when I updated 'DOSE', the latest version is 3.12.0 in bioconda. So I have no idea about this, maybe it 's a gap of update in R 3.6?
hope for your reply .

**Comment by huerqiang** [comment]
The latest version of DOSE available is 3.13.1 in the github: https://github.com/YuLab-SMU/DOSE.
You can install it by using: devtools::install_github("YuLab-SMU/DOSE").

**Comment by rusher321** [comment]
Thanks, it worked

**Comment by littleju777** [comment]
Hi,

I can't install DOSE in  R 4.1.1, could you provide an older version of HDO.db?
