### ISSUE TITLE
emapplot does not work using compareCluster object 

### ISSUE THREAD

**Issue by pdichiaro** [YuLab-SMU/enrichplot#38]
I used the sample and example from https://yulab-smu.github.io/clusterProfiler-book/chapter12.html.

![Screenshot from 2020-02-02 21-45-08](https://user-images.githubusercontent.com/50377927/73615084-5864c000-4605-11ea-9758-8041ba14b117.png)

R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by huerqiang** [comment]
> I used the sample and example from https://yulab-smu.github.io/clusterProfiler-book/chapter12.html.
> 
> ![Screenshot from 2020-02-02 21-45-08](https://user-images.githubusercontent.com/50377927/73615084-5864c000-4605-11ea-9758-8041ba14b117.png)
> 
> R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
> Copyright (C) 2019 The R Foundation for Statistical Computing
> Platform: x86_64-pc-linux-gnu (64-bit)

Please install the latest version of enrichplot: `remotes::install_github("YuLab-SMU/enrichplot")`
