### ISSUE TITLE
Customizable color scales

### ISSUE THREAD

**Issue by paulklemm** [YuLab-SMU/enrichplot#4]
Awesome package so far, I really like it.

I do not fancy the default color scales though. Can you make them customizable?

**Comment by GuangchuangYu** [comment]
yes, use ggplot2.

e.g.

```r
require(DOSE)
require(enrichplot)
require(viridis)
data(geneList)
x = enrichDO(names(geneList)[1:100])
dotplot(x) + scale_color_viridis()
```

If you have any bettor color scale scheme, don't hesitate to let me know. I may change the default color scale if I agree with you. :)

**Comment by paulklemm** [comment]
I have a couple of suggestions.

### Mind sequential and diverging scales

I would strongly argue against using a diverging color scale sequential ranges. For example, the diverging color scale for the `emaplot` shows three colors whereas it should be a gradient between two colors.
![screen shot 2018-02-09 at 16 28 41](https://user-images.githubusercontent.com/2169489/36035122-4c8cd012-0db6-11e8-8515-ab8b9b006e1b.png)

I would change it to `scale_color_gradient` . 
![screen shot 2018-02-09 at 16 48 10](https://user-images.githubusercontent.com/2169489/36036032-048abcd6-0db9-11e8-9584-b5e907a78f12.png)

### Only use `scale_color_gradient` for sequential scales

Currently for the `dotplot` actually shows a sequential scale for the sequential p-value (which is also mapped in `emaplot` to color so however you decide, you should keep the color consistent) from red to blue. I would keep `scale_color_gradient` because it's easier to understand since it doesn't mix colors.

### Mind color blind people

You currently use a sequential color scale from green → red for the `cnetplot`. I would change it to a diverging color scale since fold change is on a diverging scale. I would suggest blue → black → red. Green → black → red is not recommended since it cannot be distinguished with the most common type of color blindness.

**Comment by paulklemm** [comment]
If you want to I can make a pull request with reworked color scales.

**Comment by GuangchuangYu** [comment]
PR is welcome @paulklemm .

**Comment by nitishkumarmishra** [comment]
Hi, 
I am getting this error for enrichmap, ReactomePA and clusterProfiler

Error : object 'scale_type' is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package 'enrichplot'
* removing 'C:/Users/nitish.mishra/Documents/R/win-library/3.5/enrichplot'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by GuangchuangYu** [comment]
```
> scale_type
function (x)
UseMethod("scale_type")
<bytecode: 0x7ff3d45d3968>
<environment: namespace:ggplot2>
```

pls check your installation.

**Comment by arider2** [comment]
Hi,

Adding +scale_color_viridis() or +scale_colour_gradient() to a dotplot works just fine, but trying this with cnetplot just makes the colours black and white. Why is this?

**Comment by BS2018** [comment]
I want to increase the size of the text of the emapplot object. I know that with geom_node_text function I can edit the text. However, I am unable to remove the original text that comes with the emapplot function. Any advice will be highly helpful:)

**Comment by sparsepix** [comment]
Setting scale_color_viridis for dotplot() works fine but seems to be ignored for heatplot. it is really difficult to distinguish slightly up- and downregulated genes using the default color scheme :(

**Comment by angiachino** [comment]
Having the same issue as @sparsepix : heatplot is not affected by _scale_color_viridis_ and other _scale_color_ functions.
Here is a minimum working example (notice that the two graphs look identical even though they should not):
```
library(DOSE)

library(enrichplot)

library(ggplot2)

data(geneList)

de <- names(geneList)[abs(geneList) > 2]

edo <- enrichDGN(de)

edox <- setReadable(edo, 'org.Hs.eg.db', 'ENTREZID')

p1 <- heatplot(edox, foldChange=geneList)

p2 <- heatplot(edox, foldChange=geneList) + viridis::scale_color_viridis()

cowplot::plot_grid(p1, p2, ncol=1, labels=LETTERS[1:2])
```
![bar](https://user-images.githubusercontent.com/57718980/127775554-75239e86-f416-4f64-bf6f-c07d5c9d11dc.png)

**Comment by huerqiang** [comment]
@sparsepix You should use `viridis::scale_fill_viridis`
```r
p2 <- heatplot(edox, foldChange=geneList) + viridis::scale_fill_viridis()
```
