### ISSUE TITLE
cnetplot with gene sets of interest instead of n categories

### ISSUE THREAD

**Issue by abberclark** [YuLab-SMU/enrichplot#45]
Is it possible to have the input for cnetplot be a list of gene sets from an enrichment result instead of specifying the number of gene sets to plot? For example, my enrichment result (from enrichGO) has migration and adhesion terms and I would like to visualize the connections of the genes within these terms. However, since the terms are not sequential in the result, I don't think I currently can do that. 

Any advice is greatly appreciated! Thanks!

**Comment by TatianaV12** [comment]
I have the same question. I have some enriched terms of interest but some of them are are not include on the top of the list and I would like to plot them together in a cnetplot.

I would appreciate your help.

**Comment by huerqiang** [comment]
You can adjust the enrichGO results like this, and then draw the graph： 
goid <- c("GO:0140014", "GO:0048285", "GO:0000819")
 ego@result <- ego@result[goid, ]
 cnetplot(ego)

**Comment by GuangchuangYu** [comment]
@huerqiang don't teach people using `@`, they may screwed up the result.

**Comment by GuangchuangYu** [comment]
```
cnetplot(ego, showCategory=your_interest_gos)
```

should work.
