### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by wangmhan** [YuLab-SMU/enrichplot#50]
Hi,

I'm trying to install enrichplot on server, with R version 3.6.3, but failed.

The error log is:
ERROR: failed to lock directory ‘/*/R/x86_64-pc-linux-gnu-library/3.6’ for modifying

Do you know how to fix it? Thanks!

**Comment by huerqiang** [comment]
Please try: Delete the  00LOCK folder in R/library and install again. Or run R as an administrator.

**Comment by wangmhan** [comment]
Thanks, the problem is fixed.
