### ISSUE TITLE
Recreating the plot in R using GSEA desktop output

### ISSUE THREAD

**Issue by mintang92** [YuLab-SMU/enrichplot#53]
Dear Yu lab,

I am trying to use gseaplot2 to recreate the figures created by the GSEA desktop to obtain better resolution. I ran the GSEA in the desktop version and used the generated xls. file as input for gseaplot2. It cannot be executed. Can you clarify the format of input data for gseaplot2 and what is the geneSetID it requires?

Thank you,
Min

**Comment by huerqiang** [comment]
@mintang92 This tutorial may be helpful to you：https://yulab-smu.github.io/clusterProfiler-book/chapter12.html#ridgeline-plot-for-expression-distribution-of-gsea-result

**Comment by mintang92** [comment]
Thank you!
