### ISSUE TITLE
ridgeplot shows some pathway with no ridges

### ISSUE THREAD

**Issue by hellozzzw** [YuLab-SMU/enrichplot#63]
![image](https://user-images.githubusercontent.com/15883697/94637497-4ceba500-030a-11eb-90c6-7608fc34dd85.png)
Dear Yu ,
     When using ridgeplot to draw a picture, it seems that there are always several items that cannot be drawn for gseresult. This is very strange. After I edit the source code, I still can't draw it.

```
d1 =data.frame(gs2val.df[sapply(gs2val, length)>2,],stringsAsFactors = F)
d1$category = as.character(d1$category)
ggplot(  d1  , aes_string(x="value", y="category", fill=fill))+
  ggridges::geom_density_ridges( ) +
   scale_fill_continuous(low="red", high="blue", name = fill,guide=guide_colorbar(reverse=TRUE)) +
  xlab(NULL) + ylab(NULL) +  theme_dose()
```

Thanks  a lot!

**Comment by huerqiang** [comment]
Please provide repeatable code and data.

**Comment by AnzeLovse** [comment]
I had the same issue with `ridgeplot()` and setting `core_enrichment = FALSE` resolved the issue. Noticeably, all terms with missing ridges had only two of core enriched genes. Unfortunately I can not provide the data to reproduce this.

**Comment by hellozzzw** [comment]
您好！          我是张文静，您的来信我已收到。          祝工作生活都愉快~

**Comment by Martina-H** [comment]
Thank you @AnzeLovse! This fixed it for me too!

**Comment by hellozzzw** [comment]
您好！          我是张文静，您的来信我已收到。          祝工作生活都愉快~

**Comment by hellozzzw** [comment]
您好！          我是张文静，您的来信我已收到。          祝工作生活都愉快~
