### ISSUE TITLE
Feature request: adding new option "orderBy" to ridgeplot

### ISSUE THREAD

**Issue by shenwei356** [YuLab-SMU/enrichplot#76]
Hi all,

Thanks for this great package. It would be great if an option "orderBy" could be added to `ridgeplot`, just like that in `dotplot`.

The default option is sorting by `NES`:

       j <- order(x$NES[i], decreasing=FALSE)

Wei

**Comment by GuangchuangYu** [comment]
fixed by <https://github.com/YuLab-SMU/enrichplot/pull/84/>.

**Comment by shenwei356** [comment]
Thank you!
