### ISSUE TITLE
Error in has_pairsim(x) :    Term similarity matrix not available. Please use pairwise_termsim function to deal with the results of enrichment analysis.

### ISSUE THREAD

**Issue by lc822** [YuLab-SMU/enrichplot#79]
Hi,

I am getting this error when running the `emapplot` function on a `compareClusterResult` object.

> Error in has_pairsim(x) : 
>  Term similarity matrix not available. Please use pairwise_termsim function to deal with the results of enrichment analysis.

The code is as follows:
```
compare_cluster_KEGG <- compareCluster(geneClusters = gene_module_list, 
                                       fun = "enrichKEGG",
                                       organism = "hsa",
                                       pAdjustMethod = "BH",
                                       universe = expressed_genes_all$entrezgene_id,
                                       qvalueCutoff = 0.05)

emapplot(compare_cluster_KEGG)
```

Should I just be running the `pairwise_termsim` function as I couldn't see this in the manual?

Many thanks,
Lucy

**Comment by huerqiang** [comment]
`x2 <- pairwise_termsim(compare_cluster_KEGG)
emapplot(x2)
`

**Comment by lc822** [comment]
Thank you.  And for GO terms, would you recommend running `godata` first as below?

```
d <- GOSemSim::godata("org.Hs.eg.db", ont = "BP")    
compare_cluster_GO_emap <- enrichplot::pairwise_termsim(compare_cluster_GO, semData = d)
emapplot(compare_cluster_GO_emap)
```

**Comment by huerqiang** [comment]
godata is only needed when you use the semantic similarity method(one of "Resnik", "Lin", "Rel", "Jiang" and "Wang") to calculate the similarity matrix.
```r
d <- GOSemSim::godata("org.Hs.eg.db", ont = "BP")    
compare_cluster_GO_emap <- enrichplot::pairwise_termsim(compare_cluster_GO, semData = d,  method="Wang")
emapplot(compare_cluster_GO_emap)
```

**Comment by lc822** [comment]
Ok thank you.
