### ISSUE TITLE
Can we get access to the scripts underlying the package?

### ISSUE THREAD

**Issue by NeginValizadegan** [YuLab-SMU/enrichplot#82]
Since enrichplot cannot be used with data frame, I am trying to use another package called igraph to create some networks of gene and pathways. However, when I have too many pathways and genes, everything is cluttered. I am wondering how you set it out so that your plots are laid out very nicely.

**Comment by gabrieljmarques** [comment]
Hi,
I had the same problem.
But if you go here in github, there are all the codes behind the functions: https://github.com/YuLab-SMU/enrichplot/tree/master/R
Hope it helps u

**Comment by huerqiang** [comment]
@NeginValizadegan  You can use some operations to convert the data frame to a format that can be used by enrichplot. If you provide your data, I could try it for you.
