### ISSUE TITLE
cnetplot doesn't work

### ISSUE THREAD

**Issue by EzicJ** [YuLab-SMU/enrichplot#83]
Hello,

I have used your package previously, it is really amazing!

I wanted to re-do an analysis today that I have previously done a couple of weeks ago, and cnetplot doesn't work.
I haven't updated R in the meantime (Using R 4.0.2)

When I want to use it I get the following error:

`Error in loadNamespace(name) : there is no package called ‘ggnewscale’
`
Other functions work, only cnetplot doesn't. I also tried the example in the help file, it also doesn't work.

I hope you can help me.

Best,

Jasko

**Comment by huerqiang** [comment]
Just install the `ggnewscale` package.
