### ISSUE TITLE
emaplot for KEGG and Reactome enrichments

### ISSUE THREAD

**Issue by fmjabato** [YuLab-SMU/enrichplot#85]
Currently, at commit "Remove the calculation of similarity from emaplot" (8e2a740d6b1fd3aa6ee06f9b9f422ff903a93dc7), you have changed the emaplot function to receive and external terms similarity set which can be obtained using pairwise_termsim for GO sets.

Our problem is that we also use empalot to print KEGG (clusterProfiler) and Reactome (ReactomePA) enrichResult and compareClusterResult objects.

We only can find examples for GO sets and not for these other enrichments. We know that KEGG and Reactome can offer problems for these Index of Content and semantic similarity orientation of your update, but can you offer an option to obtain these SemSim objects or use the removed similarity calculation which emaplot already uses before named commit?

Thank you

**Comment by huerqiang** [comment]
For enrichment results other than GO and DO, please use `pairwise_termsim(ekegg)`

**Comment by fmjabato** [comment]
Perfect! It's all working.

I've boserved that results with no significant results (under p-value threshold) launch errors at pairwise_termsim and (obviusly) at emaplot calls. Maybe warnings and an empty plot could be more suitable for usage in automatized pipelines? But it'is just my opinion, your design is very good and we're very grateful for all functionalities you have implemented along your packages.

With this, I close the issue.

Thank you
